apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
spec:
  containers:
  - name: alpine-container
    image: alpine
    # command: ["/bin/sh", "-c", "while true; do echo 'Hello from Alpine'; sleep 10; done"]
    command: ["sleep", "infinity"]

# kubectl exec -it alpine-pod -- /bin/sh