apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx-container
    imagem: nginx:latest
    ports:
      - name: web
        containerPort: 80

# kubectl apply -f nginx.yaml
