apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-deployment
spec:
  selector:
    matchLabels:
      app: oracle
  replicas: 2
  template:
    metadata:
      labels:
        app: oracle
    spec:
      containers:
      - name: oracle
        image: oraclelinux
        imagePullPolicy: Always
        command: ["sleep", "infinity"]