---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiss-army-knife
  namespace: swiss-army-knife
spec:
  selector:
    matchLabels:
      app: swiss-army-knife
  replicas: 1
  template:
    metadata:
      labels:
        app: swiss-army-knife
        disable-gcp-cloud-logging: "true"
    spec:
      containers:
        - name: swiss-army-knife
          image: rfahham/swiss-army-knife:v1.6.0
          imagePullPolicy: Always