apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer # TYPELoadBalancer => Pegar um EXTERNAL-IP 
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
