apiVersion: apps/v1
kind: Deployment
metadata:
  name: airportnames-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: rmerces/airportnames
        ports:
        - containerPort: 8080

# kubectl port-forward deployment/airportnames-deployment 8080:80