apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer # TYPELoadBalancer => Pegar um EXTERNAL-IP 
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80

# kubectl apply -f service.yaml  

# ✗ kubectl get svc                 
# NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
# nginx-service   ClusterIP   100.126.214.9   <none>        80/TCP    39s

# kubectl port-forward svc/nginx-service 8080:80

# http://localhost:8080/